global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ml-model-monitoring'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ml-model-api'
    static_configs:
      - targets: ['api:8000']
