apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model-api
  labels:
    app: ml-model-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-model-api
  template:
    metadata:
      labels:
        app: ml-model-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: ml-model-api
        image: ${DOCKER_REGISTRY:-localhost}/ml-model-api:${IMAGE_TAG:-latest}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_NAME
          value: "${MODEL_NAME:-ml-model}"
        - name: MODEL_STAGE
          value: "${MODEL_STAGE:-Production}"
        - name: MLFLOW_TRACKING_URI
          value: "${MLFLOW_TRACKING_URI:-http://mlflow-service:5000}"
        - name: ENABLE_METRICS
          value: "true"
        - name: PROMETHEUS_MULTIPROC_DIR
          value: "/tmp"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws-access-key-id
              optional: true
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws-secret-access-key
              optional: true
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: aws-config
              key: aws-region
              optional: true
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: aws-config
              key: s3-bucket
              optional: true
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: model-cache
          mountPath: /app/models
      volumes:
      - name: model-cache
        emptyDir: {}